version: '3.8'
services:
  # MySQL for user-service
  mysql-user:
    image: mysql:8.4
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ro_user_db
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-user-data:/var/lib/mysql

  # Nacos
  nacos:
    image: nacos/nacos-server:v3.1.0
    container_name: nacos
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
